# Generated by Django 4.1.13 on 2024-04-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retriever', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('checked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MongoDBModel',
        ),
    ]
